-- 000001_core_schema.down.sql
DROP TABLE IF EXISTS pitfalls CASCADE;
DROP TABLE IF EXISTS problem_relationships CASCADE;
DROP TABLE IF EXISTS question_tags CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS question_types CASCADE;
DROP TABLE IF EXISTS problem_tags CASCADE;
DROP TABLE IF EXISTS problem_topics CASCADE;
DROP TABLE IF EXISTS problems CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS topics CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TYPE IF EXISTS topic_level;
DROP TYPE IF EXISTS question_format;
DROP TYPE IF EXISTS difficulty_label;
